language: python
python:
    - "3.6"
env:
  - NUMBA_DISABLE_JIT=1

before_install:
    - pip install coveralls
    - pip install qt
    - pip install pytest-qt
    - pip install pytest-xvfb==1.1.0
    - pip install pytest-ordering==0.5

install:
    - pip install -r requirements.txt
    - pip install .

script:
    - coverage run --source DataProcessingTools -m py.test -s -q

after_success:
    - coverage report
    - coveralls
